name: buskeit
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^2.0.1
  flutter_secure_storage: ^6.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.0.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.4
  smooth_page_indicator: ^1.0.0+2
  top_snackbar_flutter: ^3.0.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/buskiet.png"
  min_sdk_android: 16
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.otf
          weight: 400
        - asset: assets/fonts/Aeonik-Medium.otf
          weight: 500
        - asset: assets/fonts/Aeonik-Bold.otf
          weight: 700
        - asset: assets/fonts/Aeonik-Black.otf
          weight: 900
